ALTER TABLE `owned_vehicles`
    ADD COLUMN `vehicleid` int DEFAULT NULL,
    ADD COLUMN `stored` int(11) DEFAULT 0,
    ADD COLUMN `co_owner` varchar(255) DEFAULT NULL,
    ADD COLUMN `co_owner_name` varchar(255) DEFAULT NULL,
    ADD COLUMN `retrievable` tinyint(1) DEFAULT 1,
    ADD COLUMN `towedPrice` int(11) DEFAULT 0,
    ADD COLUMN `towedAfterPrice` int(11) DEFAULT 0,
    ADD COLUMN `towedToDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `towedOutBy` varchar(255) DEFAULT NULL,
    ADD COLUMN `isTowedOut` tinyint(1) DEFAULT 0,
    ADD COLUMN `vehicleGarage` int(11) DEFAULT 1,
    ADD COLUMN `vehicleImpound` int(11) DEFAULT 1,
    ADD COLUMN `impoundReason` varchar(255) DEFAULT NULL,
    ADD COLUMN `job` varchar(20) DEFAULT NULL,
    ADD COLUMN `gang` varchar(20) DEFAULT NULL,
    ADD COLUMN `jobGrade` int(11) DEFAULT 0,
    ADD COLUMN `jobPrivate` TEXT DEFAULT NULL,
    ADD COLUMN `gangGrade` int(11) DEFAULT 0,
    ADD COLUMN `gangPrivate` TEXT DEFAULT NULL,
    ADD COLUMN `gangLocked` varchar(20) DEFAULT NULL,
    ADD COLUMN `jobLocked` varchar(20) DEFAULT NULL,
    ADD COLUMN `deformation` varchar(300) DEFAULT NULL;